# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab551e57680f194ffdf8fa641ccac8159ab6616c799aac7a3db487bfd2269e04d454f2b5ecc774a1fcbe188280275f695594bee137fb172a76fb113f359391e

test:
  secret_key_base: 2a2383a6d3d644e78e5f337f0d7003c5a6790e40ac6c23128dc4dd534cb0e2f728d59a39115b47e64e0f911408c9ee7c8735bf1d0dd96b6dca6eee75f862d25a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
